### ISSUE TITLE
Modificación del Perfil

### ISSUE THREAD

**Issue by Adrianaleon** [Flavor-Fiesta/frontend#24]
Como usuario registrado, quiero poder modificar la información de mi perfil para mantener mis datos actualizados.

**Criterios de Aceptación:**

El usuario puede acceder a la opción "Mi perfil" desde el icono de perfil (avatar) en la parte superior de la interfaz.
Al seleccionar "Mi perfil", el usuario es dirigido a una página donde puede ver y editar su información personal, como nombre, dirección de correo electrónico, número de teléfono, etc.
El usuario puede guardar los cambios realizados en su perfil.
El sistema valida la información ingresada (por ejemplo, formato de correo electrónico).
El usuario recibe una notificación en pantalla y por correo electrónico confirmando que los cambios en su perfil se han guardado exitosamente.
El diseño de la página de perfil debe ser responsivo, adaptándose a diferentes dispositivos y tamaños de pantalla.
La interfaz debe ser intuitiva y fácil de usar para facilitar la modificación de la información del perfil.

![Image](https://github.com/Flavor-Fiesta/frontend/assets/91282953/7b432d73-324a-4c83-b57c-d01512792504)

**Comment by yoserfenix** [comment]
trae la informacion y puede editarlo
