### ISSUE TITLE
Visualizar Productos por Categoría

### ISSUE THREAD

**Issue by Adrianaleon** [Flavor-Fiesta/frontend#25]
Como usuario quiero ver una lista de productos filtrados por categoría para poder explorar los productos disponibles dentro de una categoría específica.

**Criterios de Aceptación:**
Se debe mostrar el nombre de la categoría en la parte superior de la página.
Cada producto debe mostrar su nombre, precio, imagen y descripción breve.
Debe haber opciones para agregar el producto al carrito o a la lista de deseos.
**Nota:** Es de aclarar que el redireccionamiento a cada una de las categorías se realizará desde el home, donde se podrá ubicar el contenedor de categorías. 

![Image](https://github.com/Flavor-Fiesta/frontend/assets/91282953/555de2e1-579e-407c-b21e-95db2b55408e)

**Comment by yoserfenix** [comment]
ya muestra los productos con sus respectivas categorias
