### ISSUE TITLE
Pagina de Productos "Tienda"

### ISSUE THREAD

**Issue by Adrianaleon** [Flavor-Fiesta/frontend#26]
Como usuario
Quiero ver todos los productos disponibles en la tienda
Para explorar las opciones y hacer mi selección de compra.

**Criterios de Aceptación:**
Debe mostrar todos los productos con su nombre, precio, imagen y una opción para agregar al carrito o a la lista de deseos.
Debe permitir la navegación a páginas de producto individuales para más detalles.

![Image](https://github.com/Flavor-Fiesta/frontend/assets/91282953/126aae9d-6c4d-4276-bccb-c2568d1ff7d9)

**Comment by yoserfenix** [comment]
ya muestra todos los productos
